---
title: "⋆All About Mental Health⋆"
description: | 
 All the info you need
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

⋆What is mental health?
Mental health includes our emotional, psychological, and social well-being. It affects how we think, feel, and act. It also helps determine how we handle stress, relate to others, and make healthy choices.1 Mental health is important at every stage of life, from childhood and adolescence through adulthood.

⋆Why is mental health important?
Mental Health is important because it can sometimes have an effect on our physical health as well.

⋆Can your mental health change over time?
Yes, it’s important to remember that a person’s mental health can change over time, depending on many factors.  When the demands placed on a person exceed their resources and coping abilities, their mental health could be impacted. For example, if someone is working long hours, caring for a relative, or experiencing economic hardship, they may experience poor mental health.

⋆What causes mental illness?
There is no single cause for mental illness. A number of factors can contribute to risk for mental illness, such as

-Adverse Childhood Experiences, such as trauma or a history of abuse (for example, child abuse, sexual assault, witnessing violence, etc.)
-Experiences related to other ongoing (chronic) medical conditions, such as cancer or diabetes
-Biological factors or chemical imbalances in the brain
-Use of alcohol or drugs
-Having feelings of loneliness or isolation

